shuffle:
  name: Shuffle pool(s)
  description: Pick a new random entry for the given pool sensor(s).
  fields:
    entity_id:
      description: One or more pool sensor entity IDs.
      example: sensor.pools_text_hello

reload:
  name: Reload pool(s)
  description: Reload underlying files/folders and pick a new entry.
  fields:
    entity_id:
      description: One or more pool sensor entity IDs.

reset_stats:
  name: Reset stats
  description: Reset debug counters for the given pool sensor(s).
  fields:
    entity_id:
      description: One or more pool sensor entity IDs.
